// This file was generated by counterfeiter
package nfsdriverfakes

import (
	"sync"

	"github.com/lds-cf/nfsdriver/nfsvoltools"
	"github.com/lds-cf/nfsdriver/nfsvoltools/voltoolshttp"
)

type FakeNfsRemoteClientFactory struct {
	NewRemoteClientStub        func(url string) (nfsvoltools.VolTools, error)
	newRemoteClientMutex       sync.RWMutex
	newRemoteClientArgsForCall []struct {
		url string
	}
	newRemoteClientReturns struct {
		result1 nfsvoltools.VolTools
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNfsRemoteClientFactory) NewRemoteClient(url string) (nfsvoltools.VolTools, error) {
	fake.newRemoteClientMutex.Lock()
	fake.newRemoteClientArgsForCall = append(fake.newRemoteClientArgsForCall, struct {
		url string
	}{url})
	fake.recordInvocation("NewRemoteClient", []interface{}{url})
	fake.newRemoteClientMutex.Unlock()
	if fake.NewRemoteClientStub != nil {
		return fake.NewRemoteClientStub(url)
	} else {
		return fake.newRemoteClientReturns.result1, fake.newRemoteClientReturns.result2
	}
}

func (fake *FakeNfsRemoteClientFactory) NewRemoteClientCallCount() int {
	fake.newRemoteClientMutex.RLock()
	defer fake.newRemoteClientMutex.RUnlock()
	return len(fake.newRemoteClientArgsForCall)
}

func (fake *FakeNfsRemoteClientFactory) NewRemoteClientArgsForCall(i int) string {
	fake.newRemoteClientMutex.RLock()
	defer fake.newRemoteClientMutex.RUnlock()
	return fake.newRemoteClientArgsForCall[i].url
}

func (fake *FakeNfsRemoteClientFactory) NewRemoteClientReturns(result1 nfsvoltools.VolTools, result2 error) {
	fake.NewRemoteClientStub = nil
	fake.newRemoteClientReturns = struct {
		result1 nfsvoltools.VolTools
		result2 error
	}{result1, result2}
}

func (fake *FakeNfsRemoteClientFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newRemoteClientMutex.RLock()
	defer fake.newRemoteClientMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeNfsRemoteClientFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ voltoolshttp.NfsRemoteClientFactory = new(FakeNfsRemoteClientFactory)
